[settings]
timeout = 120
provider = "native"

[relaychain]
default_command = "./target/release/polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1000
cumulus_based = true
chain = "asset-hub-rococo-local"

# collator 1 - normal
[[parachains.collators]]
name = "collator1"
validator = true
command = "./target/release/polkadot-parachain"
args = ["--force-authoring"]

# collator 2 - isolated (for held tx testing)
[[parachains.collators]]
name = "collator2"
validator = true
command = "./target/release/polkadot-parachain"
args = ["--force-authoring", "--reserved-only", "--rpc-methods", "unsafe"]
