[settings]
timeout = 120
provider = "native"

[relaychain]
default_command = "./target/release/polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1000
cumulus_based = true
chain = "asset-hub-rococo-local"

# collator 1 - normal (also used for spec building)
[[parachains.collators]]
name = "collator-normal"
validator = true
command = "./target/release/polkadot-parachain"
args = ["--force-authoring"]

# collator 2 - isolated with held queue (submit held tx here)
[[parachains.collators]]
name = "collator-held"
validator = true
command = "./target/release/polkadot-omni-node"
args = [
    "--force-authoring",
    "--enable-held-queue"
]
